In [6]:
import numpy as np
import pandas as pd
import random
import re
import matplotlib.pyplot as plt

In [155]:
dataSet_1 = pd.read_csv("sub-borougharea-medianhouseholdincome2017 (1).csv")
dataSet_2 = pd.read_csv('sub-borougharea-medianrentall2017.csv')
dataSet_2

,Sub-Borough Area,2000,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Greenwich Village/Financial District,1711.171288,1411.546860,2138.913276,893.58885,2219.615916,989.738740,1530.785200,1275.798000,1355.465800,1517.640840,1295.420160,2734.069036,2583.599491
1,Lower East Side/Chinatown,798.938959,681.009450,940.489171,684.69795,858.691843,983.033210,1026.749203,951.729628,1121.544175,995.320072,1050.429851,1109.910423,1070.552275
2,Chelsea/Clinton/Midtown,1459.571726,1423.928850,1744.710829,800.74845,1713.967139,1909.374770,1808.238010,1964.161829,1251.199200,1486.877850,1214.456400,2257.951473,2275.688265
3,Stuyvesant Town/Turtle Bay,1765.610959,1362.018900,1904.095152,1369.39590,2057.899416,2158.818030,2124.846885,1541.589250,1303.332500,1230.519600,1518.070500,2517.651962,2582.579918
4,Upper West Side,1471.342466,780.065370,1626.693430,823.95855,1703.717502,1937.720595,1701.215292,1969.581702,1771.083028,1855.770092,1823.290320,1857.064607,2199.220246
5,Upper East Side,1815.636603,1114.379100,1927.211962,1195.32015,2041.955535,2010.285907,1981.035107,2003.184912,2074.059417,2050.233887,1335.902040,2150.773494,2294.040590
6,Morningside Heights/Hamilton Heights,897.518904,755.301390,967.256004,789.14340,1154.792478,1180.320152,1111.475521,1170.692481,1194.896353,1246.241098,1258.864850,1358.274780,1263.251685
7,Central Harlem,720.957808,755.301390,787.188219,719.51310,838.192568,835.634920,885.167065,928.966163,931.253741,940.953849,1002.964455,1068.688123,1011.417007
8,East Harlem,720.957808,705.773430,681.337562,580.25250,728.863102,803.887596,894.085625,871.515514,986.533644,907.497713,889.460247,807.957077,893.146470
9,Washington Heights/Inwood,938.716493,947.222235,1014.706298,940.00905,1070.517682,1113.424005,1159.412781,1183.700175,1135.364150,1177.237816,1265.055989,1279.952410,1329.523969
10,Mott Haven/Hunts Point,559.110137,619.099500,744.604622,371.36160,758.473166,797.084598,783.718447,786.965501,796.243210,864.632037,848.185989,872.882199,968.594916
11,Morrisania/Belmont,706.244384,742.919400,862.622021,742.72320,883.746512,922.940061,917.496845,946.309755,916.370691,959.772926,931.766361,975.937949,984.908093
12,Highbridge/South Concourse,882.805480,891.503280,967.256004,951.61410,1016.991798,1021.583532,1063.538262,1056.875156,1050.318147,1127.053611,1078.289974,1122.277113,1130.707117
13,University Heights/Fordham,904.875616,916.267260,1001.322882,916.79895,1035.213375,1054.464689,1111.475521,1051.455284,1093.904223,1055.959320,1106.150098,1134.643803,1142.942001
14,Kingsbridge Heights/Mosholu,1000.512877,1002.941190,1092.573448,986.42925,1101.266594,1104.353341,1176.135080,1172.860430,1183.202527,1169.919286,1199.017177,1224.302305,1208.194711
15,Riverdale/Kingsbridge,1077.022685,928.649250,1141.240417,638.27775,1187.819087,1222.271973,1255.287299,1268.250188,1267.185456,1314.198876,1226.877301,1337.663630,1335.641410
16,Soundview/Parkchester,897.518904,854.357310,1037.823108,812.35350,1026.102586,1057.866188,1088.064302,1150.096965,1083.273473,1092.551970,1136.073935,1149.071608,1174.548782
17,Throgs Neck/Co-op City,971.086027,0.000000,1071.889986,0.00000,1167.319812,1093.015011,1154.953501,1172.860430,1040.750471,1135.417645,1149.488068,1089.299273,1219.410020
18,Pelham Parkway,1022.583014,854.357310,1060.939918,847.16865,1102.405442,1150.840494,1167.216521,1201.043768,1222.536304,1187.692859,1265.055989,1283.044082,1289.760598
19,Williamsbridge/Baychester,1015.226301,656.245470,1120.556955,649.88280,1146.820538,1185.989317,1170.560980,1217.303385,1219.347079,1260.878158,1242.355147,1229.455093,1278.545289
20,Williamsburg/Greenpoint,882.805480,854.357310,998.889533,835.56360,1117.210474,1174.650987,1183.938820,1321.364939,1380.934486,1350.791526,1639.619875,1655.075338,1774.058056
21,Brooklyn Heights/Fort Greene,1000.512877,520.043580,1141.240417,290.12625,1223.123394,1350.395102,1541.796034,1485.045092,1628.630972,1558.846877,1675.734850,1795.231158,1820.958442
22,Bedford Stuyvesant,783.422984,606.717510,878.438786,719.51310,1031.796829,1043.126359,1062.423442,1009.180278,1107.724199,1097.779491,1105.118242,1265.524605,1317.289085
23,Bushwick,896.047562,866.739300,1001.322882,870.37875,1119.488171,1180.320152,1229.646439,1249.822621,1248.050105,1278.651731,1309.425816,1342.816417,1432.500902
24,East New York/Starrett City,907.818301,718.155420,1051.206525,603.46260,1109.238534,1106.621007,1138.231201,1130.585424,1073.705798,1157.373235,1089.640395,1136.704918,1151.098589
25,Park Slope/Carroll Gardens,1294.781370,804.829350,1626.693430,626.67270,1710.550593,1826.604961,1816.041750,1844.924632,1801.912205,1939.410434,931.083240,2094.092832,2072.793120
26,Sunset Park,1040.239123,841.975320,1185.040689,870.37875,1194.652179,1235.877969,1287.617079,1250.906595,1313.960758,1313.153372,1373.400915,1329.419170,1426.383460
27,North Crown Heights/Prospect Heights,882.805480,854.357310,1046.339828,789.14340,1094.433502,1085.078180,1186.168460,1146.845042,1143.868751,1135.417645,1204.176459,1249.035685,1385.600516
28,South Crown Heights,978.442740,1002.941190,1074.323335,928.40400,1087.600411,1096.416510,1154.953501,1147.929016,1202.337878,1195.011389,1278.470123,1290.257985,1323.406527
29,Bay Ridge,1118.220274,804.829350,1221.540915,812.35350,1251.594609,1319.781611,1311.028298,1332.204684,1322.465359,1341.381988,1372.369058,1419.077672,1467.166404
30,Bensonhurst,1054.952548,928.649250,1181.390666,754.32825,1122.904717,1085.078180,1129.312641,1206.463640,1232.103980,1232.649543,1264.024132,1305.716347,1357.052456
31,Borough Park,1069.665973,916.267260,1182.607340,800.74845,1249.316911,1241.547134,1331.095058,1286.677755,1304.393083,1353.928039,1429.121162,1394.344292,1468.185978
32,Coney Island,837.193863,619.099500,849.238604,580.25250,865.524934,942.215222,971.008204,959.317450,928.064516,956.636414,891.523960,1058.382548,1001.221271
33,Flatbush,1022.583014,1015.323180,1130.290349,998.03430,1161.625569,1157.643492,1214.038960,1236.814927,1238.482430,1244.150090,1311.489528,1351.060877,1343.797999
34,Sheepshead Bay/Gravesend,1040.239123,321.931740,1076.756683,406.17675,1094.433502,1161.044991,1167.216521,1168.524532,1238.482430,1220.103491,1290.852400,1337.663630,1327.484821
35,Brownsville/Ocean Hill,735.671233,594.335520,755.554690,522.22725,839.331416,901.397234,935.333964,902.950775,992.912094,908.543217,980.263613,887.310004,985.927667
36,East Flatbush,1010.812274,879.121290,1116.906932,847.16865,1174.152904,1166.714156,1207.350040,1164.188634,1180.013302,1247.286603,1219.654306,1257.280145,1337.680557
37,Flatlands/Canarsie,1152.061151,0.000000,1200.857454,0.00000,1241.344971,1274.428291,1264.205859,1275.838009,1282.068507,1345.564005,1303.234677,1359.305337,1384.580943
38,Astoria,1103.506849,1064.851140,1243.441051,1021.24440,1291.454309,1354.930434,1423.625116,1400.495079,1452.160514,1440.704894,1525.083810,1565.416836,1558.928028
39,Sunnyside/Woodside,1147.647123,1040.087160,1295.758043,1032.84945,1303.981644,1391.213090,1438.117776,1457.945729,1485.115841,1486.707082,1604.536756,1633.433631,1600.730545
40,Jackson Heights,1159.417863,990.559200,1331.041595,812.35350,1309.675887,1351.528935,1350.046997,1364.723920,1401.132912,1418.749304,1431.184875,1442.780494,1497.753612
41,Elmhurst/Corona,1121.162959,1077.233130,1318.874853,1125.68985,1318.786676,1393.480756,1389.065697,1397.243156,1393.691387,1412.476278,1433.248588,1475.758334,1421.285592
42,Middle Village/Ridgewood,1085.850740,854.357310,1277.507929,789.14340,1282.343521,1331.119941,1389.065697,1328.952761,1317.149983,1314.198876,1366.177920,1466.483317,1517.125510
43,Rego Park/Forest Hills,1244.755726,730.537410,1357.808428,615.06765,1412.172261,1429.763412,1467.103096,1513.228429,1462.791265,1518.072210,1534.370518,1589.119659,1604.808839
44,Flushing/Whitestone,1221.214247,0.000000,1411.342093,0.00000,1388.256440,1428.629579,1481.595755,1447.105983,1417.079038,1415.612791,1414.675172,1465.452759,1537.516982
45,Hillcrest/Fresh Meadows,1118.220274,235.257810,1288.457997,0.00000,1309.675887,1373.071762,1319.946858,1333.288659,1374.556036,1366.474090,1394.038043,1502.552829,1546.693144
46,Ozone Park/Woodhaven,1169.717260,0.000000,1349.291708,406.17675,1324.480919,1359.465766,1357.850737,1365.807894,1416.015963,1416.658295,1447.694578,1476.788892,1499.792759
47,South Ozone Park/Howard Beach,1147.647123,0.000000,1413.775442,0.00000,1403.061472,1362.867265,1441.462236,1391.823283,1389.439087,1372.747116,1433.248588,1462.361087,1472.264272
48,Bayside/Little Neck,1330.093589,0.000000,1455.142365,0.00000,1568.194519,1598.704529,1573.010994,1693.168199,1648.829398,1616.349612,1666.448142,1716.908788,1657.826666
49,Jamaica,1029.939726,0.000000,1130.290349,0.00000,1141.126295,1207.532144,1230.761259,1216.219411,1219.347079,1246.241098,1248.546286,1258.310702,1273.447421
50,Queens Village,1232.984986,0.000000,1473.392478,0.00000,1424.699595,1489.856561,1517.269995,1576.098951,1471.295865,1468.933509,1545.720939,1558.202934,1539.556129
51,Rockaways,850.435945,619.099500,989.156140,220.49595,1038.629921,1037.457194,1016.715823,1062.295029,1033.308946,1110.325542,1048.366138,1156.285510,1063.415260
52,North Shore,1029.939726,0.000000,1155.840507,0.00000,1223.123394,1154.241993,1268.665139,1183.700175,1141.742601,1119.735081,1148.456212,1207.813385,1242.860213
53,Mid-Island,1128.519671,0.000000,1259.257816,0.00000,1193.513330,1297.104951,1181.709180,1201.043768,1143.868751,1328.835936,1185.603043,1347.969205,1334.621837
54,South Shore,1147.647123,0.000000,1261.691164,0.00000,1316.508979,1377.607094,1374.573037,1253.074544,1306.519233,1293.288791,1275.374553,1212.966173,1259.173391

In [22]:
dataSet_3 = pd.read_csv('sub-borougharea-population.csv')

In [23]:
dataSet_4 = pd.read_csv('sub-borougharea-populationaged25withabachelorsdegreeorhigher.csv')

In [24]:
dataSet_5 = pd.read_csv('sub-borougharea-severecrowdingrateofrenterhouseholds1.csv')

In [25]:
dataSet_6 = pd.read_csv('communitydistrict-seriouscrimerateper1000residents.csv')

In [110]:
dataSet_2.iloc[0,3:13]

2006    2138.91
2007    893.589
2008    2219.62
2009    989.739
2010    1530.79
2011     1275.8
2012    1355.47
2013    1517.64
2014    1295.42
2015    2734.07
Name: 0, dtype: object

In [109]:
d = dict()`\
Data = pd.DataFrame(columns = ['2006','2007','2008','2009','2010','2011','2012','2013','2014','2015'])

for i in dataSet_1.index:
    s = pd.DataFrame([dataSet_1.iloc[i,5:15],dataSet_2.iloc[i,3:13],dataSet_3.iloc[i,5:15],dataSet_4.iloc[i,5:15],dataSet_6.iloc[i,3:13]])
    Data.loc[dataSet_1.iloc[i,2]] = s

ValueError: cannot set a row with mismatched columns

In [120]:
def calcuDistance(ve1,ve2):
    d = 0
    for i in dataSet_1.columns:
        if i in ['2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']:
            d += (dataSet_1.iloc[ve1][i]-dataSet_1.iloc[ve2][i])**2
    for i in dataSet_2.columns:
        if i in ['2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']:
            d += (dataSet_2.iloc[ve1][i]-dataSet_2.iloc[ve1][i])**2
    for i in dataSet_3.columns:
        if i in ['2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']:
            d += (dataSet_3.iloc[ve1][i]-dataSet_3.iloc[ve1][i])**2
    for i in dataSet_4.columns:
        if i in ['2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']:
            d += (dataSet_4.iloc[ve1][i]-dataSet_4.iloc[ve1][i])**2
    for i in dataSet_6.columns:
        if i in ['2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']:
            d += (dataSet_6.iloc[ve1][i]-dataSet_6.iloc[ve1][i])**2
    return d**(1/2)
calcuDistance(0,1)

246635.58027677116

In [124]:
def initCentroids(index, k):
    # 从数据集中随机选取k个数据返回
    dataSet = list(index)
    return random.sample(dataSet, k)
initCentroids(dataSet_1.index, 3)

[20, 45, 42]

In [133]:
def minDistance(dataSet, centroidList):

    # 对每个属于dataSet的item， 计算item与centroidList中k个质心的距离，找出距离最小的，并将item加入相应的簇类中
    clusterDict = dict() #dict保存簇类结果
    k = len(centroidList)
    for item in dataSet:
        vec1 = item
        flag = -1
        minDis = float("inf") # 初始化为最大值
        for i in range(k):
            vec2 = centroidList[i]
            distance = calcuDistance(vec1, vec2)  # error
            if distance < minDis:
                minDis = distance
                flag = centroidList[i]  # 循环结束时， flag保存与当前item最近的蔟标记
        if flag not in clusterDict.keys():
            clusterDict.setdefault(flag, [])
        clusterDict[flag].append(item)  #加入相应的类别中
    return clusterDict  #不同的类别

In [169]:
s = pd.DataFrame([np.zeros(10)],columns=['2006','2007','2008','2009','2010','2011','2012','2013','2014','2015'])
s.loc['1']=0

   2006  2007  2008  2009  2010  2011  2012  2013  2014  2015
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0

In [180]:
def get_average(l):
    s = pd.DataFrame([np.zeros(10)],columns=['2006','2007','2008','2009','2010','2011','2012','2013','2014','2015'])
    for k in ['1','2','3','4','6']:
            s.loc[k]=0
    for j in l:
        for k in ['1','2','3','4','6']:
            if k == '1':
                for i in s.columns:
                    s.loc[k][i] += dataSet_1.iloc[j][i]
            if k == '2':
                for i in s.columns:
                    s.loc[k][i] += dataSet_2.iloc[j][i]
            if k == '3':
                for i in s.columns:
                    s.loc[k][i] += dataSet_3.iloc[j][i]
            if k == '4':
                for i in s.columns:
                    s.loc[k][i] += dataSet_4.iloc[j][i]
            if k == '6':
                for i in s.columns:
                    s.loc[k][i] += dataSet_6.iloc[j][i]
    s = s.iloc[1:]
    return s/len(l)

In [183]:
def cal_diff(index,average):
    sum = 0
    for i in average.index:
        if i == '1':
            for j in average.columns:
                sum += abs(average.loc[i][j]-dataSet_1.iloc[index][j])
        if i == '2':
            for j in average.columns:
                sum += abs(average.loc[i][j]-dataSet_2.iloc[index][j])
        if i == '3':
            for j in average.columns:
                sum += abs(average.loc[i][j]-dataSet_3.iloc[index][j])
        if i == '4':
            for j in average.columns:
                sum += abs(average.loc[i][j]-dataSet_4.iloc[index][j])
        if i == '6':
            for j in average.columns:
                sum += abs(average.loc[i][j]-dataSet_6.iloc[index][j])
    return sum

In [185]:
cal_diff(1,average)

674832.3123318151

In [184]:
average = get_average([2,3,4])

In [191]:
getCentroids(clusterDict)

[21, 41, 35]

In [190]:
def getCentroids(clusterDict):
    #重新计算k个质心
    centroidList = []
    for key in clusterDict.keys():
        average = get_average(clusterDict[key])
        min_ = float('inf')
        for i in dataSet_1.index:
            if min_>cal_diff(i,average):
                min_ = cal_diff(i,average)
                target = i
        centroidList.append(target)
    return centroidList  #得到新的质心

In [138]:
def getVar(clusterDict):
    # 计算各蔟集合间的均方误差
    # 将蔟类中各个向量与质心的距离累加求和
    sum = 0.0
    for key in clusterDict.keys():
        vec1 = key
        distance = 0.0
        for item in clusterDict[key]:
            vec2 = item
            distance += calcuDistance(vec1, vec2)
        sum += distance
    return sum

In [129]:
#测试聚类效果，并可视化
def test_k_means():
    dataSet = loadDataSet()
    centroidList = initCentroids(dataSet, 4)
    clusterDict = minDistance(dataSet, centroidList)
    # # getCentroids(clusterDict)
    # showCluster(centroidList, clusterDict)
    newVar = getVar(centroidList, clusterDict)
    oldVar = 1  # 当两次聚类的误差小于某个值是，说明质心基本确定。

    times = 2
    while abs(newVar - oldVar) >= 0.00001:
        centroidList = getCentroids(clusterDict)
        clusterDict = minDistance(dataSet, centroidList)
        oldVar = newVar
        newVar = getVar(centroidList, clusterDict)
        times += 1
        showCluster(centroidList, clusterDict)

In [145]:
centroidList=initCentroids(dataSet_1.index, 3)

In [156]:
centroidList=[24,6,49]

In [160]:
minDistance(dataSet_1.index, centroidList)[49][5:]

[15,
 17,
 19,
 21,
 25,
 29,
 34,
 37,
 38,
 39,
 40,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54]

In [199]:
new = getVar(clusterDict)
old = 0
while abs(new - old) >= 10:
    old = getVar(clusterDict)
    centroidList=getCentroids(clusterDict)
    clusterDict=minDistance(dataSet_1.index, centroidList)
    new = getVar(clusterDict)

In [200]:
clusterDict

{25: [0, 2, 3, 4, 5, 25, 48, 50, 54],
 49: [1,
  6,
  15,
  17,
  18,
  19,
  20,
  21,
  26,
  27,
  28,
  29,
  30,
  31,
  33,
  34,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  49,
  51,
  52,
  53],
 35: [7, 8, 9, 10, 11, 12, 13, 14, 16, 22, 23, 24, 32, 35]}

In [204]:
l = []
for i in [0, 2, 3, 4, 5, 25, 48, 50, 54]:
    l.append(dataSet_1.iloc[i]['Sub-Borough Area'])

In [205]:
l

['Greenwich Village/Financial District',
 'Chelsea/Clinton/Midtown',
 'Stuyvesant Town/Turtle Bay',
 'Upper West Side',
 'Upper East Side',
 'Park Slope/Carroll Gardens',
 'Bayside/Little Neck',
 'Queens Village',
 'South Shore']

In [206]:
l = []
for i in [1,
  6,
  15,
  17,
  18,
  19,
  20,
  21,
  26,
  27,
  28,
  29,
  30,
  31,
  33,
  34,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  49,
  51,
  52,
  53]:
    l.append(dataSet_1.iloc[i]['Sub-Borough Area'])
l

['Lower East Side/Chinatown',
 'Morningside Heights/Hamilton Heights',
 'Riverdale/Kingsbridge',
 'Throgs Neck/Co-op City',
 'Pelham Parkway',
 'Williamsbridge/Baychester',
 'Williamsburg/Greenpoint',
 'Brooklyn Heights/Fort Greene',
 'Sunset Park',
 'North Crown Heights/Prospect Heights',
 'South Crown Heights',
 'Bay Ridge',
 'Bensonhurst',
 'Borough Park',
 'Flatbush',
 'Sheepshead Bay/Gravesend',
 'East Flatbush',
 'Flatlands/Canarsie',
 'Astoria',
 'Sunnyside/Woodside',
 'Jackson Heights',
 'Elmhurst/Corona',
 'Middle Village/Ridgewood',
 'Rego Park/Forest Hills',
 'Flushing/Whitestone',
 'Hillcrest/Fresh Meadows',
 'Ozone Park/Woodhaven',
 'South Ozone Park/Howard Beach',
 'Jamaica',
 'Rockaways',
 'North Shore',
 'Mid-Island']

In [ ]:
l = []
for i in [0, 2, 3, 4, 5, 25, 48, 50, 54]:
    l.append(dataSet_1.iloc[i]['Sub-Borough Area'])